### ISSUE TITLE
Not working with function aliases

### ISSUE THREAD

**Issue by gabrielcolson** [ServerlessLife/serverless-spy#51]
If an alias is added to the stack (`myLambda.addAlias("live")`), the synth fails with the following error:
```
node_modules/serverless-spy/lib/src/ServerlessSpy.ts:415
      `${r.toString()}_${a.name.toString()}`;
           ^
TypeError: Cannot read properties of undefined (reading 'toString')
    at layerKey (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:[41](https://github.com/joinsezame/stripe-esg/actions/runs/12370441921/job/34524404087?pr=25#step:10:42)5:12)
    at ServerlessSpy.getExtensionForRuntime (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:416:31)
    at ServerlessSpy.internalSpyLambda (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:741:[44](https://github.com/joinsezame/stripe-esg/actions/runs/12370441921/job/34524404087?pr=25#step:10:45))
    at ServerlessSpy.internalSpyNode (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:386:12)
    at ServerlessSpy.internalSpyNodes (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:226:12)
    at ServerlessSpy.spy (/home/runner/work/stripe-esg/stripe-esg/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:220:10)
    at new StripeEsg (/home/runner/work/stripe-esg/stripe-esg/src/stripe-esg.ts:264:21)
    at Object.<anonymous> (/home/runner/work/stripe-esg/stripe-esg/src/main.ts:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1[46](https://github.com/joinsezame/stripe-esg/actions/runs/12370441921/job/34524404087?pr=25#step:10:47)9:14)
    at Module.m._compile (/home/runner/work/stripe-esg/stripe-esg/node_modules/ts-node/src/index.ts:1618:23)
```

I have to disable `spyLambda` to make it work:
```typescript
serverlessSpy.spy({
  spyLambda: false,
})
```
```json
"serverless-spy": "^2.2.7"
"aws-cdk": "^2.173.0"
```

**Comment by ServerlessLife** [comment]
The issue is fixed. Thank you again for reporting it.

PS: There is also new support for Node 22, so some libraries have also been updated.
