### ISSUE TITLE
Error: There is already a Construct with name 'Extension' in ServerlessSpy [ServerlessSpy]

### ISSUE THREAD

**Issue by gabrielcolson** [ServerlessLife/serverless-spy#53]
If you use multiple versions of node in your functions, the extension is created multiple times with the same resource id. In our case because the custom resource created by the `NodejsFunction` for the log retention is in NODE_18 and we use NODE_20.

I guess a fix would either be:
- do not add the runtime version in the [`layerKey`](https://github.com/ServerlessLife/serverless-spy/blob/main/src/ServerlessSpy.ts#L414) (only `node` or `python`, not `NODE_18` or `NODE_20`)
- add the runtime to the [resource id](https://github.com/ServerlessLife/serverless-spy/blob/main/src/ServerlessSpy.ts#L456)

Full stack trace:
```
Error: There is already a Construct with name 'Extension' in ServerlessSpy [ServerlessSpy]
    at Node.addChild (.../node_modules/constructs/src/construct.ts:430:13)
    at new Node (.../node_modules/constructs/src/construct.ts:71:17)
    at new Construct (.../node_modules/constructs/src/construct.ts:482:17)
    at new Resource (.../node_modules/aws-cdk-lib/core/lib/resource.js:1:1309)
    at new LayerVersion (.../node_modules/aws-cdk-lib/aws-lambda/lib/layers.js:1:1846)
    at ServerlessSpy.getExtensionForRuntime (.../node_modules/serverless-spy/lib/src/ServerlessSpy.ts:456:11)
    at ServerlessSpy.internalSpyLambda (.../node_modules/serverless-spy/lib/src/ServerlessSpy.ts:746:44)
    at ServerlessSpy.internalSpyNode (.../node_modules/serverless-spy/lib/src/ServerlessSpy.ts:386:12)
    at ServerlessSpy.internalSpyNodes (.../node_modules/serverless-spy/lib/src/ServerlessSpy.ts:226:12)
    at ServerlessSpy.spy (.../node_modules/serverless-spy/lib/src/ServerlessSpy.ts:220:10)
```

**Comment by ServerlessLife** [comment]
Thank you for the bug report and detailed analysis.

I will try to resolve it as soon a possible.

**Comment by ServerlessLife** [comment]
The bug is fixed. Thank you again for reporting it.
