### ISSUE TITLE
Support node 18 lambda

### ISSUE THREAD

**Issue by CorentinDoue** [ServerlessLife/serverless-spy#9]
The interceptor layer can't be used on node 18 lambdas

```
Error: This lambda function uses a runtime that is incompatible with this layer (nodejs18.x is not in [nodejs12.x, nodejs14.x, nodejs16.x])
    at NodejsFunction.addLayers (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/aws-cdk-lib@2.58.1_constructs@10.1.205/node_modules/aws-cdk-lib/aws-lambda/lib/function.js:1:14439)
    at ServerlessSpy.internalSpyLambda (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/serverless-spy@1.0.4_aws-cdk-lib@2.58.1_constructs@10.1.205/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:665:10)
    at ServerlessSpy.internalSpyNode (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/serverless-spy@1.0.4_aws-cdk-lib@2.58.1_constructs@10.1.205/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:364:12)
    at ServerlessSpy.internalSpyNodes (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/serverless-spy@1.0.4_aws-cdk-lib@2.58.1_constructs@10.1.205/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:245:12)
    at ServerlessSpy.spy (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/serverless-spy@1.0.4_aws-cdk-lib@2.58.1_constructs@10.1.205/node_modules/serverless-spy/lib/src/ServerlessSpy.ts:239:10)
    at new AppStack (/Users/cdoue/www-dev/projects/cdk-integration-tests/lib/app-stack.ts:124:19)
    at Object.<anonymous> (/Users/cdoue/www-dev/projects/cdk-integration-tests/bin/app.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/Users/cdoue/www-dev/projects/cdk-integration-tests/node_modules/.pnpm/ts-node@10.9.1_@types+node@10.17.27_typescript@4.9.4/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

Subprocess exited with error 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ServerlessLife** [comment]
On it.

**Comment by CorentinDoue** [comment]
> On it.

Me too 😅

**Comment by ServerlessLife** [comment]
Version 1.1 with Node 18 is deployed. 

I am sorry I did not use your PR because I had already done most of the work before you created the PR.

I really appreciate the effort.
